name: SAC

agent:
  _target_: stable_baselines3.sac.SAC
  policy: "MlpPolicy"
  env: ${task.env}
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  ent_coef: "auto"
  target_entropy: "auto"
  verbose: 0
  seed: ${seed}
  device: ${device}

