name: SAC

agent:
  _target_: stable_baselines3.sac.SAC
  _partial_: true
  policy: "MlpPolicy"
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  ent_coef: ${task.sac_ent_coef}
  target_entropy: "auto"
  verbose: 0
  seed: ${seed}
  device: ${device}
