name: "AntRunning-v0"
params: "freq_rate=1&time_step=0.02"

eval_freq: 5000
batch_size: 256

medium_reward: 2000
expert_reward: 4000
random_samples: 1000000
medium_samples: 1000000
expert_samples: 1000000