name: "BoundaryInvertedDoublePendulumBalancing-v0"

freq_rate: 1
real_time_scale: 0.02
integrator: "euler"

params: "freq_rate=${task.freq_rate}&integrator=${task.integrator}&real_time_scale=${task.real_time_scale}"

env:
  _target_: gym.make
  id: ${task.name}
  freq_rate: ${task.freq_rate}
  real_time_scale: ${task.real_time_scale}
  integrator: ${task.integrator}


# sac
sac_ent_coef: 0.5
start_steps: 1000

# eval
n_eval_episodes: 10
eval_freq: 1000

# num steps
num_steps: 3000000

medium_reward: 400
expert_reward: 950
uniform_sample_num: 100000
random_sample_num: 100000
medium_sample_num: 100000
expert_sample_num: 100000
