name: "BoundaryInvertedPendulumSwingUp-v0"
freq_rate: 1
time_step: 0.02

params: "freq_rate=${task.freq_rate}&time_step=${task.time_step}"
env:
   _target_: gym.make
   id: ${task.name}
   freq_rate: 1
   time_step: 0.02
   new_step_api: false

# sac
sac_ent_coef: 0.5
start_steps: 1000
eval_freq: 10

# num steps
num_steps: 1000000

medium_reward: 400
expert_reward: 950
uniform_sample_num: 0
random_sample_num: 0
medium_sample_num: 0
expert_sample_num: 0