name: "HalfCheetahRunning-v0"

freq_rate: 1
real_time_scale: 0.02
integrator: "euler"

params: "freq_rate=${task.freq_rate}&integrator=${task.integrator}&real_time_scale=${task.real_time_scale}"

env:
  _target_: gym.make
  id: ${task.name}
  freq_rate: ${task.freq_rate}
  real_time_scale: ${task.real_time_scale}
  integrator: ${task.integrator}

# sac
start_steps: 5000
eval_freq: 10

# num steps
num_steps: 10000000

medium_reward: 10000
expert_reward: 15000
random_sample_num: 1000000
medium_sample_num: 1000000
expert_sample_num: 1000000
