from gym.envs.registration import (
    registry,
    register,
    make,
    spec,
    load_env_plugins as _load_env_plugins,
)

# Hook to load plugins from entry points
_load_env_plugins()

# Classic
# ----------------------------------------
register(
    id="CartPoleBalancing-v0",
    entry_point="emei.envs.classic_control:CartPoleBalancingEnv",
    max_episode_steps=500,
)
register(
    id="CartPoleSwingUp-v0",
    entry_point="emei.envs.classic_control:CartPoleSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="ContinuousCartPoleBalancing-v0",
    entry_point="emei.envs.classic_control:ContinuousCartPoleBalancingEnv",
    max_episode_steps=500,
)
register(
    id="ContinuousCartPoleSwingUp-v0",
    entry_point="emei.envs.classic_control:ContinuousCartPoleSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="ChargedBallCentering-v0",
    entry_point="emei.envs.classic_control:ChargedBallCenteringEnv",
    max_episode_steps=500,
)
register(
    id="ContinuousChargedBallCentering-v0",
    entry_point="emei.envs.classic_control:ContinuousChargedBallCenteringEnv",
    max_episode_steps=1000,
)

# Mujoco
# ----------------------------------------
register(
    id="ReboundInvertedPendulumSwingUp-v0",
    entry_point="emei.envs.mujoco:ReboundInvertedPendulumSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="ReboundInvertedPendulumBalancing-v0",
    entry_point="emei.envs.mujoco:ReboundInvertedPendulumBalancingEnv",
    max_episode_steps=1000,
)
register(
    id="BoundaryInvertedPendulumSwingUp-v0",
    entry_point="emei.envs.mujoco:BoundaryInvertedPendulumSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="BoundaryInvertedPendulumBalancing-v0",
    entry_point="emei.envs.mujoco:BoundaryInvertedPendulumBalancingEnv",
    max_episode_steps=1000,
)
register(
    id="ReboundInvertedDoublePendulumSwingUp-v0",
    entry_point="emei.envs.mujoco:ReboundInvertedDoublePendulumSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="ReboundInvertedDoublePendulumBalancing-v0",
    entry_point="emei.envs.mujoco:ReboundInvertedDoublePendulumBalancingEnv",
    max_episode_steps=1000,
)
register(
    id="BoundaryInvertedDoublePendulumSwingUp-v0",
    entry_point="emei.envs.mujoco:BoundaryInvertedDoublePendulumSwingUpEnv",
    max_episode_steps=1000,
)
register(
    id="BoundaryInvertedDoublePendulumBalancing-v0",
    entry_point="emei.envs.mujoco:BoundaryInvertedDoublePendulumBalancingEnv",
    max_episode_steps=1000,
)
register(
    id="HopperRunning-v0",
    entry_point="emei.envs.mujoco:HopperRunningEnv",
    max_episode_steps=1000,
)
register(
    id="Walker2dRunning-v0",
    entry_point="emei.envs.mujoco:Walker2dRunningEnv",
    max_episode_steps=1000,
)
register(
    id="AntRunning-v0",
    entry_point="emei.envs.mujoco:AntRunningEnv",
    max_episode_steps=1000,
)
register(
    id="HalfCheetahRunning-v0",
    entry_point="emei.envs.mujoco:HalfCheetahRunningEnv",
    max_episode_steps=1000,
)
register(
    id="HumanoidRunning-v0",
    entry_point="emei.envs.mujoco:HumanoidRunningEnv",
    max_episode_steps=1000,
)
register(
    id="SwimmerRunning-v0",
    entry_point="emei.envs.mujoco:SwimmerRunningEnv",
    max_episode_steps=1000,
)
